database:
  host: localhost
  user: gafka
  password: 192205a9-58a7-4b7c-bd79-eab828e39eea
  DBName: gafka
  Port: 5432
  SSLMode: disable
kafka:
  brokers:
    - localhost:9092  # Assuming Kafka is running locally for practice
  topics:
    - Orderbook
    - Trades
  consumer:
    group_id: gafka-consumer
    auto_offset_reset: earliest  # Read messages from the beginning if no offset is stored
    enable_auto_commit: true      # Automatically commit offsets at intervals
  producer:
    acks: all  # Wait for the full set of in-sync replicas to acknowledge the message
    retries: 3
    retry_backoff_ms: 100  # Time to wait between retries
  # Additional common settings
  max_poll_records: 500        # Max number of records per poll for a consumer
  session_timeout_ms: 10000    # Consumer session timeout
  request_timeout_ms: 30000    # Timeout for client requests to Kafka brokers
